typography_spectrum: 0.014587739948183298
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.15453346562571824
  lightness: 0.10342210880480707
  saturation: 0.5034211936872452
  rhythmicContrast: 0.6544322313275188
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5221860886085778
analytics:
  google: null
  facebook: null
  twitter: null
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/506b8327-30a5-4894-a95d-ef478be4e29a.jpg'
name: kingcomplex
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/cbf82a3c-7834-4fcc-a61c-4ae0248675c0.jpg'
title: King Complex
purpose: []
